[package]
name = "plutus-halo2-verifier-gen"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
serde_json = "1.0.113"
blake2b_simd = "1.0.2"
handlebars = "6.1.0"
itertools = "0.14.0"
hex = "0.4.3"
log = "0.4.22"
env_logger = "0.11.5"
rand_core = { package = "rand_core", version = "0.6.4" }
serde = { version = "1.0.219", features = ["derive"] }
rand = "0.8"
rand_chacha = "0.3.1"
anyhow = "1.0.100"
clap = { version = "4", features = ["derive"] }
atms-halo2 = { git = "https://github.com/input-output-hk/sidechains-zk/", package = "atms-halo2", branch = "midnight-zk", features = ["circuit-params"] }
midnight-circuits = { version = "=6.0.0", default-features=false }
midnight-curves = { version = "=0.2.0" }
midnight-proofs = { version = "=0.7.0" }
midnight-zk-stdlib = { version = "=1.0.0" }
group = "0.13"
ff = "0.13.0"
base64 = "0.13.1"
num-bigint = "0.4.6"
sha2 = "0.10.9"
num-traits = "0.2.19"
num-integer = "0.1.46"

[features]
plutus_debug = []
